# Generated by Django 4.2.18 on 2025-09-07 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantillaNotificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("pedido_confirmado", "Pedido Confirmado"),
                            ("pedido_enviado", "Pedido Enviado"),
                            ("pedido_entregado", "Pedido Entregado"),
                            ("pedido_cancelado", "Pedido Cancelado"),
                            ("registro_usuario", "Registro de Usuario"),
                            ("recuperar_password", "Recuperar Contraseña"),
                            ("stock_bajo", "Stock Bajo"),
                            ("promocion", "Promoción"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Tipo de Notificación",
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                            ("sms", "SMS"),
                        ],
                        max_length=20,
                        verbose_name="Canal",
                    ),
                ),
                (
                    "asunto",
                    models.CharField(
                        help_text="Para email. Puede usar variables como {nombre}, {pedido_id}",
                        max_length=200,
                        verbose_name="Asunto",
                    ),
                ),
                (
                    "mensaje",
                    models.TextField(
                        help_text="Contenido del mensaje. Puede usar variables como {nombre}, {pedido_id}, {total}",
                        verbose_name="Mensaje",
                    ),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Plantilla de Notificación",
                "verbose_name_plural": "Plantillas de Notificaciones",
                "unique_together": {("tipo", "canal")},
            },
        ),
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("pedido_confirmado", "Pedido Confirmado"),
                            ("pedido_enviado", "Pedido Enviado"),
                            ("pedido_entregado", "Pedido Entregado"),
                            ("pedido_cancelado", "Pedido Cancelado"),
                            ("registro_usuario", "Registro de Usuario"),
                            ("recuperar_password", "Recuperar Contraseña"),
                            ("stock_bajo", "Stock Bajo"),
                            ("promocion", "Promoción"),
                        ],
                        max_length=50,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                            ("sms", "SMS"),
                        ],
                        max_length=20,
                        verbose_name="Canal",
                    ),
                ),
                (
                    "destinatario",
                    models.CharField(
                        help_text="Email o número de teléfono",
                        max_length=200,
                        verbose_name="Destinatario",
                    ),
                ),
                (
                    "asunto",
                    models.CharField(blank=True, max_length=200, verbose_name="Asunto"),
                ),
                ("mensaje", models.TextField(verbose_name="Mensaje")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("enviada", "Enviada"),
                            ("fallida", "Fallida"),
                            ("reintentando", "Reintentando"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "intentos",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Intentos de Envío"
                    ),
                ),
                (
                    "max_intentos",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Máximo Intentos"
                    ),
                ),
                (
                    "fecha_envio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Envío"
                    ),
                ),
                (
                    "error_mensaje",
                    models.TextField(blank=True, verbose_name="Mensaje de Error"),
                ),
                (
                    "pedido_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID del Pedido"
                    ),
                ),
                (
                    "producto_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID del Producto"
                    ),
                ),
                (
                    "metadatos",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadatos Adicionales"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionNotificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_habilitado",
                    models.BooleanField(default=True, verbose_name="Email Habilitado"),
                ),
                (
                    "whatsapp_habilitado",
                    models.BooleanField(
                        default=True, verbose_name="WhatsApp Habilitado"
                    ),
                ),
                (
                    "sms_habilitado",
                    models.BooleanField(default=False, verbose_name="SMS Habilitado"),
                ),
                (
                    "pedidos_habilitado",
                    models.BooleanField(
                        default=True, verbose_name="Notificaciones de Pedidos"
                    ),
                ),
                (
                    "promociones_habilitado",
                    models.BooleanField(
                        default=True, verbose_name="Notificaciones de Promociones"
                    ),
                ),
                (
                    "stock_habilitado",
                    models.BooleanField(
                        default=False, verbose_name="Notificaciones de Stock"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_notificaciones",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Notificación",
                "verbose_name_plural": "Configuraciones de Notificaciones",
            },
        ),
    ]
