# Generated by Django 4.2.18 on 2025-09-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notificaciones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantillanotificacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("pedido_confirmado", "Pedido Confirmado"),
                    ("pedido_enviado", "Pedido Enviado"),
                    ("pedido_entregado", "Pedido Entregado"),
                    ("pedido_cancelado", "Pedido Cancelado"),
                    ("registro_usuario", "Registro de Usuario"),
                    ("recuperar_password", "Recuperar Contraseña"),
                    ("stock_bajo", "Stock Bajo"),
                    ("promocion", "Promoción"),
                ],
                max_length=50,
                verbose_name="Tipo de Notificación",
            ),
        ),
    ]
