repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: mixed-line-ending
        args: [--fix=lf]

-   repo: https://github.com/psf/black
    rev: 23.9.0
    hooks:
    -   id: black
        language_version: python3

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        args: [--profile=black]

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-bugbear, flake8-comprehensions]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    -   id: mypy
        additional_dependencies: [django-stubs, types-python-dateutil, types-requests, types-Pillow]
        args: [--ignore-missing-imports, --disallow-untyped-defs]

-   repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        args: [--skip=B101,B404]

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        name: bandit (files)
        args: ["-r", "-ll"]
        exclude: ".*_test\.py$"

-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v2.4.5
    hooks:
    -   id: python-safety-dependencies-check
        args: ["-r", "requirements.txt"]

-   repo: https://github.com/python-poetry/poetry
    rev: "1.5.1"
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-export
        args: ["-f", "requirements.txt", "--output", "requirements.txt", "--without-hashes"]

-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]
        args: []  # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]
