services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      # Monta el directorio local del frontend dentro del contenedor
      - ./frontend:/app
      # Usa un volumen para node_modules para evitar que se sobrescriba desde el host
      - /app/node_modules
    restart: unless-stopped
    networks:
      - frontend_net

networks:
  frontend_net:
    driver: bridge

