version: '3.9'

services:
  test:
    build:
      context: .
      target: development
    environment:
      - DJANGO_SETTINGS_MODULE=floreria_cristina.settings.testing
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/test_db
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             pytest -v --cov=. --cov-report=xml --cov-report=term-missing"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app
    networks:
      - backend

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_test_data:/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_test_data:
  redis_test_data:
