# Generated by Django 4.2.18 on 2025-08-25 17:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ocasion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
            ],
            options={
                "verbose_name": "Ocasión",
                "verbose_name_plural": "Ocasiones",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoFlor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
            ],
            options={
                "verbose_name": "Tipo de Flor",
                "verbose_name_plural": "Tipos de Flores",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ZonaEntrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "costo_envio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Costo de envío",
                    ),
                ),
                (
                    "envio_gratis_desde",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Envío gratis desde",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
            ],
            options={
                "verbose_name": "Zona de Entrega",
                "verbose_name_plural": "Zonas de Entrega",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="producto",
            name="envio_gratis",
            field=models.BooleanField(default=False, verbose_name="Envío Gratis"),
        ),
        migrations.AddField(
            model_name="producto",
            name="es_adicional",
            field=models.BooleanField(default=False, verbose_name="Es Adicional"),
        ),
        migrations.AddField(
            model_name="producto",
            name="ocasiones",
            field=models.ManyToManyField(
                blank=True,
                related_name="productos",
                to="catalogo.ocasion",
                verbose_name="Ocasiones",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="tipo_flor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productos",
                to="catalogo.tipoflor",
                verbose_name="Tipo de Flor",
            ),
        ),
    ]
