# Generated by Django 4.2.7 on 2026-02-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_update_heroslide_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='publicar_en_redes',
            field=models.BooleanField(default=False, help_text='Marcar para incluir este producto en las publicaciones automáticas de Facebook/Instagram', verbose_name='Publicar en Redes Sociales'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_ultima_publicacion',
            field=models.DateTimeField(blank=True, help_text='Fecha de la última vez que se publicó en redes sociales', null=True, verbose_name='Última publicación en redes'),
        ),
    ]
