# Generated by Cascade

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_enabled', models.BooleanField(default=False)),
                ('vacation_from', models.DateField(default=datetime.date(2026, 1, 1))),
                ('vacation_until', models.DateField(default=datetime.date(2026, 1, 31))),
                ('reopen_date', models.DateField(default=datetime.date(2026, 2, 1))),
                (
                    'vacation_message',
                    models.TextField(
                        blank=True,
                        default='Cerrado por vacaciones. Tomamos pedidos a partir del 01/02.',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
    ]
