# Generated by Django 4.2.7 on 2026-01-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField()),
                ('source_lang', models.CharField(default='es', max_length=5)),
                ('target_lang', models.CharField(max_length=5)),
                ('translated_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Traducción',
                'verbose_name_plural': 'Traducciones',
                'indexes': [models.Index(fields=['source_text', 'target_lang'], name='core_transl_source__idx')],
                'unique_together': {('source_text', 'source_lang', 'target_lang')},
            },
        ),
    ]
