# Generated by Django 5.0.6 on 2025-07-05 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comprador', models.CharField(blank=True, help_text='Nombre de quien realiza la compra (si es invitado)', max_length=100, null=True)),
                ('telefono_comprador', models.CharField(blank=True, help_text='Teléfono de quien realiza la compra para notificaciones (si es invitado)', max_length=20, null=True)),
                ('anonimo', models.BooleanField(default=False)),
                ('dedicatoria', models.TextField()),
                ('nombre_destinatario', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono_destinatario', models.CharField(max_length=30)),
                ('fecha_entrega', models.DateField()),
                ('franja_horaria', models.CharField(choices=[('mañana', 'Mañana (9-12)'), ('tarde', 'Tarde (16-20)')], max_length=20)),
                ('instrucciones', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('preparando', 'Preparando'), ('en_camino', 'En camino'), ('entregado', 'Entregado')], default='recibido', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('medio_pago', models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('paypal', 'PayPal'), ('transferencia', 'Transferencia Bancaria')], default='transferencia', max_length=30)),
                ('regalo_anonimo', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoAccesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('accesorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.accesorio')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido')),
                                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
            ],
        ),
    ]
