# Generated by Django 4.2.18 on 2025-07-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_remove_accesorio_descripcion_accesorio_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoaccesorio',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
