# Generated by Django 4.2.18 on 2025-07-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pedidos", "0003_pedidoaccesorio_precio_pedidoitem_precio"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="confirmado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pedido",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
