# Generated by Django 4.2.18 on 2025-07-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pedidos", "0004_pedido_confirmado_pedido_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="estado_pago",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("approved", "Aprobado"),
                    ("rejected", "Rechazado"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
    ]
