# Generated by Django 4.2.18 on 2025-07-06 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalogo", "0001_initial"),
        ("pedidos", "0005_pedido_estado_pago"),
    ]

    operations = [
        migrations.CreateModel(
            name="PedidoProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="pedidos.pedido",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogo.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto del pedido",
                "verbose_name_plural": "Productos del pedido",
            },
        ),
    ]
