# Generated by Django 4.2.7 on 2026-03-08 22:10

from django.db import migrations, models
import secrets


def generar_tokens_existentes(apps, schema_editor):
    """Generar tokens para pedidos existentes"""
    Pedido = apps.get_model('pedidos', 'Pedido')
    for pedido in Pedido.objects.filter(token_acceso__isnull=True):
        pedido.token_acceso = secrets.token_urlsafe(16)
        pedido.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_pedido_tipo_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='token_acceso',
            field=models.CharField(blank=True, help_text='Token único para acceder al pedido sin login', max_length=32, null=True, unique=True),
        ),
        migrations.RunPython(generar_tokens_existentes, migrations.RunPython.noop),
    ]
