# Generated by Django 5.0.6 on 2025-07-13 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
                ('pedidos', '0008_pedido_metodo_envio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoaccesorio',
            name='accesorio',
        ),
        migrations.RemoveField(
            model_name='pedidoaccesorio',
            name='pedido',
        ),
        migrations.DeleteModel(
            name='Accesorio',
        ),
        migrations.DeleteModel(
            name='PedidoAccesorio',
        ),
    ]
