# Generated by Django 4.2.18 on 2025-07-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pedidos", "0009_remove_pedidoaccesorio_accesorio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="ciudad",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="codigo_postal",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="email_comprador",
            field=models.EmailField(
                blank=True,
                help_text="Email de quien realiza la compra (si es invitado)",
                max_length=254,
                null=True,
            ),
        ),
    ]
