# Generated by Django 4.2.18 on 2025-09-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pedidos", "0010_pedido_ciudad_pedido_codigo_postal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="numero_pedido",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="estado",
            field=models.CharField(
                choices=[
                    ("recibido", "Recibido"),
                    ("preparando", "Preparando"),
                    ("en_camino", "En camino"),
                    ("entregado", "Entregado"),
                    ("cancelado", "Cancelado"),
                ],
                default="recibido",
                max_length=20,
            ),
        ),
    ]
