"""
Django settings for floreria_cristina project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ
import dj_database_url

# Initialize environment variables
env = environ.Env()
env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-iqrk-k9+a7=+pj^w=a^10*coqt=tqj1sf^&!s6$^li541g^(i+')

# Railway detection
RAILWAY_ENVIRONMENT = env('RAILWAY_ENVIRONMENT', default=None)
IS_RAILWAY = RAILWAY_ENVIRONMENT is not None

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG debe ser False en producción (Railway)
DEBUG = env.bool('DEBUG', default=False if IS_RAILWAY else True)

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'web',
    'testserver',
    '.railway.app',  # Permitir todos los subdominios de Railway
    *env.list('ALLOWED_HOSTS', default=[]),  # Dominios personalizados desde variable de entorno
]

# Configuración para funcionar detrás de un proxy inverso (Nginx)
# Estas directivas le indican a Django que confíe en las cabeceras que Nginx le envía.
USE_X_FORWARDED_HOST = True
# ==============================================================================
# CORS CONFIGURATION
# ==============================================================================

# Configuración CORS para Docker con Nginx y Railway
# Orígenes permitidos específicos (requerido cuando usamos credentials)
CORS_ALLOWED_ORIGINS = [
    'http://localhost',
    'http://localhost:3000',
    'http://localhost:80',
    'https://floreriayviverocristian.up.railway.app',  # Frontend en Railway (ACTUALIZADO)
    'https://frontend-production-0b0b.up.railway.app',  # Frontend antiguo (mantener por compatibilidad)
    'https://frontend-production-7249.up.railway.app',  # Frontend antiguo (mantener por compatibilidad)
    *env.list('CORS_ALLOWED_ORIGINS', default=[]),  # Dominios personalizados desde variable de entorno
]
CORS_ALLOW_CREDENTIALS = True  # Permitir cookies y sesiones

# Cabeceras permitidas
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-http-method-override',
    'x-api-key',  # Agregado para carritos abandonados y n8n
    'cache-control',  # Agregado para permitir control de caché
    'pragma',  # Agregado para compatibilidad con caché
]

# Métodos HTTP permitidos
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Exponer cabeceras personalizadas
CORS_EXPOSE_HEADERS = [
    'Content-Type',
    'X-CSRFToken',
]

# Si en el futuro necesitas que cualquier sitio pueda consultar tu API (no recomendado para producción sin autenticación)
# podrías usar:
# CORS_ORIGIN_ALLOW_ALL = True



CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://web:8000',
    'http://localhost',  # Permitir el origen público a través de Nginx
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'https://*.railway.app',  # Railway domains
    *env.list('CSRF_TRUSTED_ORIGINS', default=[]),  # Dominios personalizados desde variable de entorno
]

# Eximir APIs del carrito y usuarios del CSRF
CSRF_EXEMPT_URLS = [
    r'^/api/carrito/.*',
    r'^/api/usuarios/.*',
    r'^/api/pedidos/.*',
    r'^/api/catalogo/.*',
]

# Configuración de CSRF y Cookies según entorno
if IS_RAILWAY or not DEBUG:
    # Producción - Configuración segura
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = 'Lax'
else:
    # Desarrollo local - Configuración permisiva
    CSRF_COOKIE_SECURE = False
    CSRF_COOKIE_HTTPONLY = False
    SESSION_COOKIE_SECURE = False
    SESSION_COOKIE_SAMESITE = None

CSRF_USE_SESSIONS = False
SESSION_COOKIE_HTTPONLY = True
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_NAME = 'sessionid'
SESSION_SAVE_EVERY_REQUEST = True

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'UNAUTHENTICATED_USER': None,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}


# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
]

THIRD_PARTY_APPS = [
    'cloudinary_storage',  # Re-enabled for Railway with Cloudinary
    'cloudinary',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'compressor',
    'debug_toolbar',
    'django_celery_beat',
]

LOCAL_APPS = [
    'core',
    'catalogo',
    'carrito',
    'pedidos',
    'usuarios',
    'notificaciones',
    'admin_simple',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS + [
    'crispy_forms',
    'crispy_bootstrap5',
    'widget_tweaks',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
]

# ==============================================================================
# AUTHENTICATION CONFIGURATION
# ==============================================================================

AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)

# Django Allauth Configuration
SITE_ID = 1
LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'mandatory' 
ACCOUNT_SESSION_REMEMBER = True


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise para archivos estáticos en Railway
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'floreria_cristina.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.admin_context.admin_stats',
            ],
        },
    },
]

WSGI_APPLICATION = 'floreria_cristina.wsgi.application'

# Using default User model with profile extension

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Cart session ID
CART_SESSION_ID = 'cart'

# Configuración de la base de datos
# Railway proporciona DATABASE_URL automáticamente
if IS_RAILWAY:
    # En Railway, usar DATABASE_URL
    # dj_database_url.config() buscará DATABASE_URL del entorno automáticamente
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=False  # Railway usa conexiones internas sin SSL
        )
    }
else:
    # Configuración local (Docker o desarrollo)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env('POSTGRES_DB', default='floreria_cristina_dev'),
            'USER': env('POSTGRES_USER', default='floradmin'),
            'PASSWORD': env('POSTGRES_PASSWORD', default='florpassword'),
            'HOST': env('POSTGRES_HOST', default='db'),  # 'db' en Docker, 'localhost' fuera de Docker
            'PORT': '5432',
            'CONN_MAX_AGE': 0,  # Deshabilitar conexiones persistentes para el wizard
            'OPTIONS': {
                'connect_timeout': 30,
                'application_name': 'floreria_cristina_dev',
                'options': '-c statement_timeout=30000',  # 30 segundos de timeout
            },
        }
    }

# Deshabilitar el pool de conexiones para el wizard
DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True

# Configuración para cerrar conexiones inactivas

# Configuración de conexiones persistentes
if not DEBUG:
    CONN_HEALTH_CHECKS = True
    CONN_MAX_AGE = 600  # 10 minutos
    CONN_HEALTH_CHECK_INTERVAL = 60  # Verificar cada minuto


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Email Backend Configuration
# --------------------------------------------------------------------------
# Prioridad: Resend (django-anymail) > SendGrid > SMTP > Console
import logging
logger = logging.getLogger(__name__)

USE_RESEND = env.bool('USE_RESEND', default=False)
USE_SENDGRID_API = env.bool('USE_SENDGRID_API', default=False)

if USE_RESEND:
    # Usar Resend vía django-anymail (100 emails/día gratis)
    EMAIL_BACKEND = 'anymail.backends.resend.EmailBackend'
    ANYMAIL = {
        'RESEND_API_KEY': env('RESEND_API_KEY', default=''),
    }
    logger.info("📧 Usando Resend via django-anymail")
elif USE_SENDGRID_API:
    # Usar SendGrid API (legacy - agotado)
    EMAIL_BACKEND = 'notificaciones.sendgrid_backend.SendGridAPIBackend'
    SENDGRID_API_KEY = env('SENDGRID_API_KEY', default='')
    logger.info("📧 Usando SendGrid API Backend")
else:
    # Usar SMTP tradicional o console
    EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
    EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
    EMAIL_PORT = env.int('EMAIL_PORT', default=587)
    EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
    EMAIL_USE_SSL = env.bool('EMAIL_USE_SSL', default=False)
    EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
    EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
    logger.info("📧 Usando SMTP Backend")

DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='no-responder@floreriacristina.com')
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Frontend URL para links de recuperación de contraseña
FRONTEND_URL = env('FRONTEND_URL', default='http://localhost:3000')

# Configuracion de Twilio para WhatsApp
# ATENCION: En producción, usar variables de entorno para estas credenciales.
TWILIO_ACCOUNT_SID = env('TWILIO_ACCOUNT_SID', default='ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
TWILIO_AUTH_TOKEN = env('TWILIO_AUTH_TOKEN', default='your_auth_token')
TWILIO_WHATSAPP_NUMBER = env('TWILIO_WHATSAPP_NUMBER', default='+14155238886')  # Número de sandbox o comprado
TWILIO_SMS_NUMBER = env('TWILIO_SMS_NUMBER', default='')  # Número para SMS

# Configuración Mercado Pago
MERCADOPAGO = {
    'ACCESS_TOKEN': os.getenv('MERCADOPAGO_ACCESS_TOKEN', os.getenv('MP_ACCESS_TOKEN', 'TEST-1234567890123456-123456-1234567890abcdef1234567890abcdef123456')),
    'PUBLIC_KEY': os.getenv('MERCADOPAGO_PUBLIC_KEY', os.getenv('MP_PUBLIC_KEY', 'TEST-12345678-1234-1234-1234-123456789012')),
    'AUTO_RETURN': 'approved',
    'SANDBOX': os.getenv('MP_SANDBOX_MODE', 'false').lower() == 'true'  # false by default for production
}

# Configuración PayPal
PAYPAL = {
    'MODE': os.getenv('PAYPAL_MODE', 'sandbox'),  # 'sandbox' o 'live'
    'CLIENT_ID': os.getenv('PAYPAL_CLIENT_ID', ''),
    'CLIENT_SECRET': os.getenv('PAYPAL_CLIENT_SECRET', ''),
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Staticfiles finders - including Django Compressor
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
]

# Django Compressor settings
COMPRESS_ENABLED = True
COMPRESS_URL = STATIC_URL
COMPRESS_ROOT = STATIC_ROOT
# Compile SCSS files to CSS using django-libsass
COMPRESS_PRECOMPILERS = (
    ('text/x-scss', 'django_libsass.SassCompiler'),
)

# ==============================================================================
# CLOUDINARY CONFIGURATION
# ==============================================================================
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': env('CLOUDINARY_CLOUD_NAME', default='dmxc6odsi'),
    'API_KEY': env('CLOUDINARY_API_KEY', default='854653671796364'),
    'API_SECRET': env('CLOUDINARY_API_SECRET', default='xWX_oc_i0E5B-50CxlfkX8C09lk'),
    'RESOURCE_TYPE': 'auto',  # Permite imágenes y videos automáticamente
}

# Media files configuration
# Note: Storage backends are configured in STORAGES setting below (Django 4.2+)
# DEFAULT_FILE_STORAGE is deprecated and conflicts with STORAGES
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# File upload settings
# Aumentar límites para permitir imágenes y videos
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100MB en bytes (para videos)
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100MB en bytes (para videos)

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'

# Authentication
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

# Allauth settings
SITE_ID = 1
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_USERNAME_REQUIRED = False
LOGIN_REDIRECT_URL = '/'  # Redirección post-login
LOGIN_URL = '/accounts/login/'
LOGOUT_REDIRECT_URL = '/accounts/login/'
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_LOGOUT_REDIRECT_URL = '/accounts/login/'

# Email settings - Configurado en línea 339 con variables de entorno
# No redefinir aquí para permitir configuración desde Railway

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Debug Toolbar
INTERNAL_IPS = [
    '127.0.0.1',
]

# Configuración del carrito
CART_SESSION_ID = 'carrito'

# Serializer personalizado para sesiones que maneja Decimal
SESSION_SERIALIZER = 'floreria_cristina.session_serializer.CustomJSONSerializer'

# Celery Configuration
if IS_RAILWAY:
    # En Railway, Celery es opcional o usa una URL diferente
    CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://localhost:6379/0')
    CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
    # Deshabilitar tareas automáticas si Redis no está disponible
    CELERY_TASK_ALWAYS_EAGER = not env.bool('CELERY_ENABLED', default=False)
else:
    # Configuración local (Docker)
    CELERY_BROKER_URL = 'redis://redis:6379/0'
    CELERY_RESULT_BACKEND = 'redis://redis:6379/0'
    CELERY_TASK_ALWAYS_EAGER = False

CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/Argentina/Buenos_Aires'

# Celery Beat Configuration
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Configuración de autenticación social
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'}
    },
    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'FIELDS': ['id', 'email', 'name']
    }
}

# ==============================================================================
# WHITENOISE CONFIGURATION (Para archivos estáticos en Railway)
# ==============================================================================
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",  # Use Cloudinary for media files
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# ==============================================================================
# SECURITY SETTINGS (Para producción en Railway)
# ==============================================================================
if IS_RAILWAY or not DEBUG:
    # HTTPS/SSL
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Security Headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'SAMEORIGIN'  # Permitir iframes del mismo origen
    SECURE_REFERRER_POLICY = 'same-origin'
    
    # Proxy headers (Railway usa proxy)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True
else:
    # Desarrollo local - configuración permisiva
    SECURE_SSL_REDIRECT = False
    X_FRAME_OPTIONS = 'SAMEORIGIN'

# ==============================================================================
# LOGGING CONFIGURATION
# ==============================================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'pedidos': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'notificaciones': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# ==============================================================================
# N8N CONFIGURATION
# ==============================================================================
N8N_WEBHOOK_URL = env('N8N_WEBHOOK_URL', default='http://localhost:5678')
N8N_API_KEY = env('N8N_API_KEY', default='')
N8N_ENABLED = env.bool('N8N_ENABLED', default=False)
